### ISSUE TITLE
Improvements: combined paths on logrotate.jobs

### ISSUE THREAD

**Issue by egarbi** [saltstack-formulas/logrotate-formula#13]
I don't know if this is even possible to achieve, but it would be great if state support something like this:
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
    sharedscripts
    postrotate
    /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
}
it would save many lines on pillars

**Comment by edwin--zhao** [comment]
update jobs.sls:
change line 23:
--- path: {{ value.get('path', key) }}
+++ path: {{ value.get('path', []) }}

update templates/job.tmpl
{% for onepath in path %}
{{ onepath }}
{%- endfor %}
{
  {% for item in data %}
  {{ item }}
  {%- endfor %}
}

now pillar you config like:
jobs:
  path:
     - /var/log/cron
     - /var/log/maillog
     - /var/log/messages
     - /var/log/secure
     - /var/log/spooler
  config:
     - xxxxx
