### ISSUE TITLE
Jobs lines start with 'u'

### ISSUE THREAD

**Issue by waynegemmell** [saltstack-formulas/logrotate-formula#41]
Hi

In salt-ssh on 2019.2 the jobs file gets filed with lines starting with 'u' as per below. 
It's got something to do with this bug https://github.com/saltstack/salt/issues/51925 but I can't work out where to put the fix. Please investigate. 

> "u'/var/log/mylog/*.log'"
> {
>   u'daily'
>   u'missingok'
>   u'rotate 120'
>   u'compress'
>   u'notifempty'
>   u'dateext'
>   u'create 660 php developers'
>   u'su php developers'
> }

**Comment by waynegemmell** [comment]
PR created

**Comment by myii** [comment]
Closing due to merged PR #42 -- thanks for that, @waynegemmell.
