### ISSUE TITLE
Add support for Ubuntu (16.04, 18.04)

### ISSUE THREAD

**Issue by grandmotivator** [saltstack-formulas/logrotate-formula#51]
Add support for Ubuntu (16.04, 18.04)

**Comment by myii** [comment]
@grandmotivator That's already there:

https://github.com/saltstack-formulas/logrotate-formula/blob/d08d9bfa06300073e768d7a7b1471af3cc89a203/kitchen.yml#L73-L75

https://github.com/saltstack-formulas/logrotate-formula/blob/d08d9bfa06300073e768d7a7b1471af3cc89a203/kitchen.yml#L108-L110

https://travis-ci.com/saltstack-formulas/logrotate-formula/builds/131610312

What's not working for you?

**Comment by grandmotivator** [comment]
ubuntu-16.04, salt-2019.2.2 - After connecting the formula, the logrotate configs in the Ubuntu system are not replaced. No errors with "state.apply".

https://github.com/saltstack-formulas/logrotate-formula/blame/master/docs/README.rst#L20 - this may be an omission, but Ubuntu is not listed here

**Comment by myii** [comment]
@grandmotivator The `README` may not be up to date but the formula definitely works on Ubuntu.  Taking the debug log for `18.04` in Travis, starting from here:

* https://travis-ci.com/saltstack-formulas/logrotate-formula/jobs/244926904#L1265

You can see that after managing the `/etc/logrotate.conf` file, all of the specific configurations are added under `/etc/logrotate.d/`.

If you can share your pillar and also what configuration files you're expecting for the formula to manage, then we can establish whether there is a bug or a misconfiguration.

**Comment by grandmotivator** [comment]
In my case all files from `/etc/logrotate.conf` and `/etc/logrotate.d/` remain unchanged after `state.apply`.

**Comment by myii** [comment]
@grandmotivator Please share your pillar and the contents of (some of) the files.

**Comment by myii** [comment]
@grandmotivator The idea is that we can prepare a failing test in Travis, to show that there's a bug.  But I need your configuration to be able to do that.

**Comment by grandmotivator** [comment]
https://drive.google.com/file/d/1uRTuaUVdDDMLnoosn4Pz3YPXZsiwzXh0/view?usp=sharing

**Comment by myii** [comment]
@grandmotivator OK, I'm using this pillar in Travis with the `18.04` and `16.04` instances to see what it produces.

**Comment by myii** [comment]
@grandmotivator All appears to be working fine: https://travis-ci.org/myii/logrotate-formula/builds/642347529.  I've even configured it to output the files after managing them:

* https://travis-ci.org/myii/logrotate-formula/jobs/642347531#L1685
* https://travis-ci.org/myii/logrotate-formula/jobs/642347532#L1604
* https://travis-ci.org/myii/logrotate-formula/jobs/642347533#L1538
* https://travis-ci.org/myii/logrotate-formula/jobs/642347535#L1565

The only thing left is your `top.sls`.  Perhaps you don't have `logrotate.jobs` included:

https://github.com/saltstack-formulas/logrotate-formula/blob/d08d9bfa06300073e768d7a7b1471af3cc89a203/kitchen.yml#L181-L187

**Comment by grandmotivator** [comment]
Why is it not enough to use just that? Without `logrotate.jobs`. Is this a feature of a formula call? Differs from the output of other formulas, for example `nginx`.

https://github.com/saltstack-formulas/logrotate-formula/blob/d08d9bfa06300073e768d7a7b1471af3cc89a203/kitchen.yml#L181-L186

**Comment by myii** [comment]
It's in the `README`:

* https://github.com/saltstack-formulas/logrotate-formula#logrotate

> Installs the `logrotate` package and service/timer/cron.

https://github.com/saltstack-formulas/logrotate-formula/blob/d08d9bfa06300073e768d7a7b1471af3cc89a203/logrotate/init.sls#L4-L7

For the jobs, you need:

* https://github.com/saltstack-formulas/logrotate-formula#logrotatejobs

> Create custom job for logrotate.

Looking inside that file, there's already an `include` for `logrotate`:

https://github.com/saltstack-formulas/logrotate-formula/blob/d08d9bfa06300073e768d7a7b1471af3cc89a203/logrotate/jobs.sls#L5-L6

So you could just use the `- logrotate.jobs` in your `top.sls` by itself, to do everything.

---

Does this solve your issue?  If so, please go ahead and close it.

**Comment by grandmotivator** [comment]
@myii thanks, its working

**Comment by myii** [comment]
You're welcome, @grandmotivator.
