### ISSUE TITLE
Include jobs.sls in init.sls?

### ISSUE THREAD

**Issue by mdschmitt** [saltstack-formulas/logrotate-formula#57]
Just wondering why jobs.sls isn't part of init.sls ..?

Is there a specific reason it's not in there?  I would think that the following line would make it so that it could be included without issue if there's no jobs definition in the pillar...
```jinja2
{% set jobs = salt['pillar.get']('logrotate:jobs', {}) %}
```

**Comment by javierbertoli** [comment]
@mdschmitt I think there is no reason for not adding it. I submitted a PR to fix it.
